// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vacina.API.Context;

#nullable disable

namespace Vacinas.API.Migrations
{
    [DbContext(typeof(ConsultaContext))]
    partial class ConsultaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vacinas.API.Model.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_consulta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "13119056774",
                            DataSolicitacao = new DateTime(2023, 4, 4, 14, 4, 32, 200, DateTimeKind.Local).AddTicks(3921),
                            Nome = "Lucas Galvão"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "56898787874",
                            DataSolicitacao = new DateTime(2023, 4, 4, 14, 4, 32, 200, DateTimeKind.Local).AddTicks(3996),
                            Nome = "Lucas Coutinho"
                        });
                });

            modelBuilder.Entity("Vacinas.API.Model.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoRelatorio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeTotalVacinados")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_relatorio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataSolicitacao = new DateTime(2023, 4, 4, 14, 4, 32, 200, DateTimeKind.Local).AddTicks(3979),
                            DescricaoRelatorio = "Relatório Vacinas Pfizer aplicadas no RJ dia 03/03/2023",
                            QuantidadeTotalVacinados = 71,
                            SolicitanteId = 1
                        },
                        new
                        {
                            Id = 2,
                            DataSolicitacao = new DateTime(2023, 4, 4, 14, 4, 32, 200, DateTimeKind.Local).AddTicks(4010),
                            DescricaoRelatorio = "Relatório Vacinas Pfizer aplicadas no RJ dia 15/03/2023",
                            QuantidadeTotalVacinados = 50,
                            SolicitanteId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
